---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-generator
  labels:
    control-plane: secret-generator
spec:
  selector:
    matchLabels:
      control-plane: secret-generator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: secret-generator
      labels:
        control-plane: secret-generator
    spec:
      containers:
      - command:
        - /usr/local/bin/secret-generator-rs
        image: locmai/secret-generator-rs:0.0.1
        imagePullPolicy: Always
        name: secret-generator
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: secret-generator
      terminationGracePeriodSeconds: 10
