---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-generator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-generator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "patch" ,"delete"]
- apiGroups: ["locmai.dev"]
  resources: ["secretgenerators", "secretgenerators/status"]
  verbs: ["get", "watch", "list", "create", "update", "patch" ,"delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-generator
subjects:
- kind: ServiceAccount
  name: secret-generator
  namespace: platform
roleRef:
  kind: ClusterRole
  name: secret-generator
  apiGroup: rbac.authorization.k8s.io
