apiVersion: locmai.dev/v1alpha1
kind: SecretGenerator
metadata:
  name: secret-generator-samples
  namespace: default
spec:
  name: secret-generator-samples
  secrets:
  - name: short-secret-sample
    length: 16
  - name: long-secret-sample
    length: 22
  backend: "kubernetes"
