name: Build Docker image with Tag

on:
  push:
    branches:    
    - 'master'
    tags:
    - 'v*'

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${{ github.repository }}/name-redactor-service:${GITHUB_REF:10}
    - name: Login to Registry
      run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to Registry
      run: docker push docker.pkg.github.com/${{ github.repository }}/name-redactor-service:${GITHUB_REF:10}
